import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ApiClientContract, ApiRouteContract } from "@providers/openapi/index.js";
import { createOpenApiDocument } from "@providers/openapi/index.js";
import { apiRouteContracts } from "../src/api-contracts.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const openApiPath = resolve(root, "src/generated/openapi.generated.json");
const clientPath = resolve(root, "src/generated/api-client.generated.ts");
const checkOnly = process.argv.includes("--check");

const openApiDocument = createOpenApiDocument({
	title: "Agent-First Template API",
	version: "0.1.0",
	routes: apiRouteContracts,
});

const outputs = [
	{
		path: openApiPath,
		content: `${JSON.stringify(openApiDocument, null, "\t")}\n`,
	},
	{
		path: clientPath,
		content: generateClient(apiRouteContracts),
	},
];

for (const output of outputs) {
	if (checkOnly) {
		const current = readFileSync(output.path, "utf-8");
		if (current !== output.content) {
			throw new Error(
				`${relative(root, output.path)} is stale. Run "pnpm api:generate" and commit the result.`,
			);
		}
		continue;
	}

	mkdirSync(dirname(output.path), { recursive: true });
	writeFileSync(output.path, output.content);
}

function generateClient(routes: readonly ApiRouteContract[]) {
	const clientRoutes = routes.filter((route) => route.client);
	const imports = mergeImports(clientRoutes.map((route) => route.client).filter(isDefined));
	const methods = clientRoutes.map(generateClientMethod).join(",\n\n");

	return `${[
		"/* eslint-disable */",
		"/* This file is generated by scripts/generate-openapi.ts. Do not edit by hand. */",
		"",
		imports,
		"",
		"export interface ApiClientOptions {",
		"\tbaseUrl?: string;",
		"\tfetch?: typeof fetch;",
		"}",
		"",
		"export interface ApiRequestOptions {",
		"\theaders?: HeadersInit;",
		"\tsignal?: AbortSignal;",
		"}",
		"",
		"export class ApiClientError extends Error {",
		"\treadonly body: unknown;",
		"\treadonly status: number;",
		"",
		"\tconstructor(status: number, body: unknown) {",
		'\t\tsuper("API request failed with HTTP " + status);',
		'\t\tthis.name = "ApiClientError";',
		"\t\tthis.status = status;",
		"\t\tthis.body = body;",
		"\t}",
		"}",
		"",
		"export function createApiClient(options: ApiClientOptions = {}) {",
		'\tconst baseUrl = options.baseUrl ?? "";',
		"\tconst fetchImpl = options.fetch ?? fetch;",
		"",
		"\treturn {",
		indent(methods, 2),
		"\t};",
		"}",
		"",
		"export const apiClient = createApiClient();",
		"",
		"async function request<TResponse>(",
		"\tfetchImpl: typeof fetch,",
		"\tbaseUrl: string,",
		"\tmethod: string,",
		"\tpath: string,",
		"\toptions: ApiRequestOptions = {},",
		"\tbody?: unknown,",
		"\tparseResponse?: (body: unknown) => TResponse,",
		"): Promise<TResponse> {",
		"\tconst response = await fetchImpl(baseUrl + path, {",
		"\t\tmethod,",
		'\t\theaders: body === undefined ? options.headers : { "Content-Type": "application/json", ...options.headers },',
		"\t\tbody: body === undefined ? undefined : JSON.stringify(body),",
		"\t\tsignal: options.signal,",
		"\t});",
		"",
		"\tif (!response.ok) {",
		"\t\tthrow new ApiClientError(response.status, await parseBody(response));",
		"\t}",
		"",
		"\tif (response.status === 204) return undefined as TResponse;",
		"\tconst responseBody = await response.json();",
		"\treturn parseResponse ? parseResponse(responseBody) : (responseBody as TResponse);",
		"}",
		"",
		"async function parseBody(response: Response) {",
		'\tconst contentType = response.headers.get("content-type") ?? "";',
		'\tif (contentType.includes("application/json")) return response.json();',
		"\treturn response.text();",
		"}",
	].join("\n")}\n`;
}

function generateClientMethod(route: ApiRouteContract) {
	const client = route.client;
	if (!client) throw new Error(`Route ${route.operationId} is missing client metadata.`);

	const params = methodParameters(client);
	const path = client.pathParamsType ? pathTemplate(route.path) : JSON.stringify(route.path);
	const parseArg = client.responseParser
		? `, (body: unknown) => ${client.responseParser}.parse(body)`
		: "";
	const bodyArg = client.requestBodyType ? ", body" : parseArg ? ", undefined" : "";
	return `${client.functionName}(${params}): Promise<${client.responseType}> {\n\treturn request<${client.responseType}>(fetchImpl, baseUrl, ${JSON.stringify(route.method.toUpperCase())}, ${path}, options${bodyArg}${parseArg});\n}`;
}

function methodParameters(client: ApiClientContract) {
	const params: string[] = [];
	if (client.pathParamsType) params.push(`params: ${client.pathParamsType}`);
	if (client.requestBodyType) params.push(`body: ${client.requestBodyType}`);
	params.push("options: ApiRequestOptions = {}");
	return params.join(", ");
}

function pathTemplate(path: string) {
	const templateStart = "$";
	const template = path.replaceAll(
		/:([A-Za-z0-9_]+)/g,
		(_match, name: string) => `${templateStart}{params.${name}}`,
	);
	return `\`${template}\``;
}

function mergeImports(clients: readonly ApiClientContract[]) {
	const importsByModule = new Map<string, Set<string>>();

	for (const client of clients) {
		for (const importSpec of client.imports ?? []) {
			const moduleKey = `${importSpec.kind ?? "type"}:${importSpec.module}`;
			const names = importsByModule.get(moduleKey) ?? new Set<string>();
			for (const name of importSpec.names) names.add(name);
			importsByModule.set(moduleKey, names);
		}
	}

	return Array.from(importsByModule.entries())
		.map(([moduleKey, names]) => {
			const [kind, module] = moduleKey.split(":");
			const sortedNames = Array.from(names).sort().join(", ");
			if (kind === "value") return `import { ${sortedNames} } from ${JSON.stringify(module)};`;
			return `import type { ${sortedNames} } from ${JSON.stringify(module)};\nexport type { ${sortedNames} } from ${JSON.stringify(module)};`;
		})
		.join("\n");
}

function indent(value: string, level: number) {
	const prefix = "\t".repeat(level);
	return value
		.split("\n")
		.map((line) => (line ? `${prefix}${line}` : line))
		.join("\n");
}

function isDefined<T>(value: T | undefined): value is T {
	return value !== undefined;
}
